[[redirects]]
  from = "/"
  to = "/blog"
  status = 301

[[redirects]]
  from = "/images/*"
  to = "/blog/images/:splat"
  status = 301

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202

[[redirects]]
  from = "/query"
  to = "https://github.com/TkDodo/react-query-beyond-the-basics"
  status = 301
  force = true
