[[redirects]]
  from = "/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/blog/favicon.ico"
  status = 200

[[redirects]]
  from = "/favicon.svg"
  to = "/blog/favicon.svg"
  status = 200

[[redirects]]
  from = "/favicon-32x32.png"
  to = "/blog/favicon-32x32.png"
  status = 200

[[redirects]]
  from = "/favicon-16x16.png"
  to = "/blog/favicon-16x16.png"
  status = 200

[[redirects]]
  from = "/apple-touch-icon.png"
  to = "/blog/apple-touch-icon.png"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/blog/images/:splat"
  status = 301

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202

[[redirects]]
  from = "/query"
  to = "https://github.com/TkDodo/react-query-beyond-the-basics"
  status = 301
  force = true
